const DB_SHEET_URL="https://docs.google.com/spreadsheets/d/1cZ2tNUGjsGbhqvd24W-eUEygm3-QhySdurFMj-W2ZXc/edit?usp=drivesdk";
const STORAGE_KEY="frontier-village-save-v3";
const OLD_STORAGE_KEYS=["frontier-village-save-v2","frontier-village-save"];
const ENDPOINT_KEY="frontier-village-sheet-endpoint";
const TOKEN_KEY="frontier-village-sheet-token";
const resourceLabels={wood:{label:"木材",icon:"🪵"},clay:{label:"泥土",icon:"🧱"},iron:{label:"鐵礦",icon:"⛓️"},crop:{label:"穀物",icon:"🌾"}};
const unitStats={clubman:{label:"棍棒兵",icon:"⚔️",attack:40,defense:20,upkeep:1,cost:{wood:95,clay:75,iron:40,crop:40}},spearman:{label:"矛兵",icon:"🛡️",attack:10,defense:35,upkeep:1,cost:{wood:80,clay:100,iron:80,crop:40}},scout:{label:"斥候",icon:"👁️",attack:0,defense:10,upkeep:1,cost:{wood:60,clay:40,iron:90,crop:50}}};
const fieldDefs=[["wood","伐木場"],["wood","伐木場"],["wood","伐木場"],["wood","伐木場"],["clay","泥坑"],["clay","泥坑"],["clay","泥坑"],["clay","泥坑"],["iron","鐵礦"],["iron","鐵礦"],["iron","鐵礦"],["iron","鐵礦"],["crop","農田"],["crop","農田"],["crop","農田"],["crop","農田"],["crop","農田"],["crop","農田"]];
const quests=[{id:"upgrade",text:"① 升級任一資源田"},{id:"train",text:"② 訓練棍棒兵"},{id:"select",text:"③ 點擊地圖上的綠洲"},{id:"attack",text:"④ 派兵攻擊"},{id:"report",text:"⑤ 查看戰報"}];
let selectedTargetId=null;
let previousHud={};
let state=loadState();
function freshState(){return{version:3,turn:1,lastTick:Date.now(),lastSaved:null,progress:{upgrade:false,train:false,select:false,attack:false,report:false},village:{id:"v1",name:"黎明河谷",x:0,y:0,resources:{wood:760,clay:760,iron:760,crop:760},fields:fieldDefs.map(([type,name],index)=>({id:`${type}_${index}`,type,name,level:1}))},troops:{clubman:12,spearman:4,scout:2},map:makeMap(),reports:[],lastBattle:null}}
function makeMap(){const tiles=[];for(let y=-3;y<=3;y+=1){for(let x=-3;x<=3;x+=1){tiles.push({id:`${x}_${y}`,x,y,type:x===0&&y===0?"village":"wild",name:x===0&&y===0?"你的村莊":"荒地",cleared:false})}}const targets=[{id:"-1_1",type:"oasis",name:"森林綠洲",bonus:"木材 +25%",animals:18,resources:{wood:120,clay:45,iron:35,crop:55}},{id:"2_-1",type:"oasis",name:"泥土綠洲",bonus:"泥土 +25%",animals:10,resources:{wood:50,clay:135,iron:40,crop:60}},{id:"1_2",type:"oasis",name:"穀物綠洲",bonus:"穀物 +25%",animals:26,resources:{wood:40,clay:60,iron:45,crop:160}},{id:"-2_-2",type:"oasis",name:"鐵礦綠洲",bonus:"鐵礦 +25%",animals:14,resources:{wood:70,clay:45,iron:140,crop:40}},{id:"3_2",type:"camp",name:"野獸營地",bonus:"小型獸群",animals:8,resources:{wood:45,clay:40,iron:25,crop:35}},{id:"-3_0",type:"camp",name:"狼穴",bonus:"小型獸群",animals:12,resources:{wood:35,clay:55,iron:40,crop:25}}];for(const target of targets){Object.assign(tiles.find(tile=>tile.id===target.id),target)}return tiles}
function loadState(){for(const key of [STORAGE_KEY,...OLD_STORAGE_KEYS]){try{const raw=localStorage.getItem(key);if(raw)return normalizeState(JSON.parse(raw))}catch{localStorage.removeItem(key)}}return freshState()}
function normalizeState(saved){const base=freshState();return{...base,...saved,version:3,progress:{...base.progress,...(saved.progress||{})},village:{...base.village,...(saved.village||{}),resources:{...base.village.resources,...(saved.village?.resources||{})},fields:Array.isArray(saved.village?.fields)&&saved.village.fields.length?saved.village.fields:base.village.fields},troops:{...base.troops,...(saved.troops||{})},reports:Array.isArray(saved.reports)?saved.reports:[],map:migrateMap(saved.map,base.map)}}
function migrateMap(savedMap,baseMap){if(!Array.isArray(savedMap)||savedMap.length!==49)return baseMap;return baseMap.map(baseTile=>{const savedTile=savedMap.find(tile=>tile.id===baseTile.id);if(!savedTile)return baseTile;if(baseTile.type==="oasis"||baseTile.type==="camp")return{...baseTile,cleared:Boolean(savedTile.cleared),animals:savedTile.cleared?0:Number(savedTile.animals??baseTile.animals)};return baseTile})}
function productionFor(field){return 16+field.level*12}
function upkeep(){return Object.entries(state.troops).reduce((sum,[unit,count])=>sum+count*unitStats[unit].upkeep,0)}
function totalTroops(){return Object.values(state.troops).reduce((sum,count)=>sum+count,0)}
function population(){return 26+state.village.fields.reduce((sum,field)=>sum+field.level,0)+Math.floor(totalTroops()/4)}
function rates(){const result={wood:0,clay:0,iron:0,crop:0};for(const field of state.village.fields)result[field.type]+=productionFor(field);result.crop=Math.max(0,result.crop-upkeep());return result}
function tickResources(){const now=Date.now();const elapsedHours=Math.max(0,(now-state.lastTick)/3600000);if(elapsedHours<.0005)return;const hourly=rates();for(const key of Object.keys(hourly))state.village.resources[key]=Math.min(9000,state.village.resources[key]+hourly[key]*elapsedHours);state.lastTick=now}
function fieldCost(field){const level=field.level;return{wood:80+level*42,clay:70+level*36,iron:55+level*31,crop:35+level*24}}
function canPay(cost){return Object.entries(cost).every(([key,value])=>state.village.resources[key]>=value)}
function pay(cost){if(!canPay(cost)){setNotice("資源不足。先等待產量累積，或挑比較便宜的項目升級。","warn");return false}for(const[key,value]of Object.entries(cost))state.village.resources[key]-=value;return true}
function upgradeField(fieldId){const field=state.village.fields.find(item=>item.id===fieldId);if(!field)return;const cost=fieldCost(field);if(!pay(cost))return;field.level+=1;state.turn+=1;state.progress.upgrade=true;saveLocal(`${field.name} 升級成功，現在是等級 ${field.level}。`,"success")}
function train(unit,amount){const cost={};for(const[key,value]of Object.entries(unitStats[unit].cost))cost[key]=value*amount;if(!pay(cost))return;state.troops[unit]+=amount;state.turn+=1;if(unit==="clubman")state.progress.train=true;saveLocal(`訓練完成：${unitStats[unit].label} x${amount}。`,"success")}
function isAttackable(tile){return(tile.type==="oasis"||tile.type==="camp")&&!tile.cleared}
function numberFrom(id){return Math.max(0,Math.floor(Number(document.getElementById(id).value)||0))}
function attack(){const target=state.map.find(tile=>tile.id===selectedTargetId);if(!target||!isAttackable(target)){setNotice("請先在地圖上點擊一個尚未清除的綠洲或野獸營地。","warn");renderBattleResult(null);return}const sent={clubman:numberFrom("sendClub"),spearman:numberFrom("sendSpear")};if(sent.clubman+sent.spearman<=0){setNotice("至少要派出一名士兵。","warn");return}if(sent.clubman>state.troops.clubman||sent.spearman>state.troops.spearman){setNotice("派出的士兵超過目前兵力，請減少數量。","warn");return}const attackPower=sent.clubman*unitStats.clubman.attack+sent.spearman*unitStats.spearman.attack;const defensePower=target.animals*23+Math.round(Math.random()*60);const victory=attackPower>=defensePower;const lossRatio=victory?Math.min(.42,defensePower/Math.max(1,attackPower)*.36):Math.min(.9,defensePower/Math.max(1,attackPower)*.58);const losses={clubman:Math.min(sent.clubman,Math.ceil(sent.clubman*lossRatio)),spearman:Math.min(sent.spearman,Math.ceil(sent.spearman*lossRatio))};state.troops.clubman-=losses.clubman;state.troops.spearman-=losses.spearman;const loot=victory?{...target.resources}:{wood:0,clay:0,iron:0,crop:0};if(victory){for(const key of Object.keys(loot))state.village.resources[key]+=loot[key];target.cleared=true;target.animals=0}else{target.animals=Math.max(1,target.animals-Math.ceil((sent.clubman+sent.spearman)/4))}const report={time:new Date().toLocaleString("zh-TW"),target:target.name,coordinate:`(${target.x}, ${target.y})`,result:victory?"勝利":"失敗",sent,losses,loot,cleared:victory};state.lastBattle=report;state.reports.unshift(report);state.reports=state.reports.slice(0,30);state.turn+=1;state.progress.attack=true;renderBattleResult(report);saveLocal(victory?`攻擊勝利：${target.name} 已清除。`:`攻擊失敗：${target.name} 還有野獸。`,victory?"success":"warn")}
function saveLocal(message="已存到瀏覽器。",tone="success"){state.lastSaved=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));setNotice(message,tone);render()}
function render(){tickResources();renderHud();renderFields();renderTroops();renderMap();renderTargetCard();renderReports();renderQuests();renderSaveInfo();renderBattleResult(state.lastBattle)}
function renderHud(){const res=state.village.resources;const hourly=rates();for(const key of["wood","clay","iron","crop"]){updateText(key,Math.floor(res[key]).toLocaleString("zh-TW"));updateText(`${key}Rate`,`+${hourly[key]}/h`);pulseHud(key,Math.floor(res[key]))}updateText("population",String(population()));updateText("soldiers",String(totalTroops()));updateText("cropUse",`耗糧 ${upkeep()}/h`);updateText("turn",String(state.turn));pulseHud("population",population());pulseHud("soldiers",totalTroops());pulseHud("turn",state.turn);const wins=state.reports.filter(report=>report.result==="勝利").length;updateText("winRate",state.reports.length?`${Math.round(wins/state.reports.length*100)}%`:"0%")}
function pulseHud(key,value){const item=document.querySelector(`[data-hud="${key}"]`);if(!item||previousHud[key]===undefined||previousHud[key]===value){previousHud[key]=value;return}previousHud[key]=value;item.classList.remove("pulse");void item.offsetWidth;item.classList.add("pulse")}
function renderFields(){document.getElementById("fieldGrid").innerHTML=state.village.fields.map(field=>{const cost=fieldCost(field);return`<button class="field-card field-${field.type}" data-field-id="${field.id}" aria-label="升級${field.name}"><span class="field-icon">${resourceLabels[field.type].icon}</span><strong>${field.name}</strong><span class="field-meta">等級 ${field.level} / 產量 +${productionFor(field)}/h</span><span class="field-cost">成本：${formatCost(cost)}</span><span class="mini-button">升級</span></button>`}).join("")}
function renderTroops(){document.getElementById("troopSummary").innerHTML=Object.entries(unitStats).map(([unit,stats])=>`<article class="troop-card"><span class="troop-icon">${stats.icon}</span><div><strong>${stats.label} x${state.troops[unit]}</strong><p>攻擊 ${stats.attack} / 防禦 ${stats.defense} / 耗糧 ${stats.upkeep}</p></div><span>${unit==="clubman"?"主攻":unit==="spearman"?"防守":"偵察"}</span></article>`).join("")}
function renderMap(){document.getElementById("mapGrid").innerHTML=state.map.map(tile=>{const selected=tile.id===selectedTargetId?" selected":"";const cleared=tile.cleared?" map-cleared":"";return`<button class="map-tile map-${tile.type}${selected}${cleared}" data-tile="${tile.id}" aria-label="${tile.name} ${tile.x},${tile.y}"><span class="tile-badge">${mapIcon(tile)}</span><strong>${tile.name}</strong><span class="tile-detail">${mapDetail(tile)}</span></button>`}).join("")}
function renderTargetCard(){const card=document.getElementById("targetCard");const target=state.map.find(tile=>tile.id===selectedTargetId);if(!target){card.textContent="請先點擊地圖上的綠洲或野獸營地。";return}if(target.type==="village"){card.innerHTML=`<div class="target-title"><span>🏠 你的村莊</span><span>(0, 0)</span></div><p>這是你的出發點，不能攻擊自己。</p>`;return}if(target.type==="wild"){card.innerHTML=`<div class="target-title"><span>🌾 荒地</span><span>(${target.x}, ${target.y})</span></div><p>荒地目前沒有敵人，也沒有戰利品。</p>`;return}card.innerHTML=`<div class="target-title"><span>${mapIcon(target)} ${target.name}</span><span>(${target.x}, ${target.y})</span></div><dl><div><dt>野獸數量</dt><dd>${target.animals}</dd></div><div><dt>狀態</dt><dd>${target.cleared?"已清除":"可攻擊"}</dd></div><div><dt>可能戰利品</dt><dd>${formatCost(target.resources)}</dd></div><div><dt>建議派兵</dt><dd>${suggestedTroops(target)} 棍棒兵以上</dd></div></dl>`}
function renderBattleResult(report){const box=document.getElementById("battleResult");if(!box)return;if(!report){box.className="battle-result muted-result";box.textContent="尚未交戰。";return}box.className=`battle-result ${report.result==="勝利"?"win":"loss"}`;box.innerHTML=`<strong>${report.result}：${report.target} ${report.coordinate}</strong><span>損失兵力：棍棒兵 ${report.losses.clubman}、矛兵 ${report.losses.spearman}</span><span>獲得資源：${formatCost(report.loot)}</span><span>${report.cleared?"目標已清除。":"目標尚未清除。"}</span>`}
function renderReports(){const list=document.getElementById("reportList");if(!state.reports.length){list.innerHTML="<li>尚無戰報。完成第一次攻擊後，結果會出現在這裡。</li>";return}list.innerHTML=state.reports.map(report=>`<li><strong>${report.result}</strong> ${report.target} ${report.coordinate} <span class="report-time">${report.time}</span><br>派出：棍棒兵 ${report.sent.clubman}、矛兵 ${report.sent.spearman}；損失：棍棒兵 ${report.losses.clubman}、矛兵 ${report.losses.spearman}<br>戰利品：${formatCost(report.loot)}；${report.cleared?"已清除":"未清除"}</li>`).join("")}
function renderQuests(){document.getElementById("questList").innerHTML=quests.map(quest=>`<li class="${state.progress[quest.id]?"done":""}">${state.progress[quest.id]?"✓ ":""}${quest.text}</li>`).join("")}
function renderSaveInfo(){const savedText=state.lastSaved?new Date(state.lastSaved).toLocaleString("zh-TW"):"尚無";updateText("lastSaved",savedText);updateText("lastSavedMini",savedText);document.getElementById("endpointInput").value=localStorage.getItem(ENDPOINT_KEY)||"";document.getElementById("tokenInput").value=localStorage.getItem(TOKEN_KEY)||""}
function mapDetail(tile){if(tile.type==="village")return"(0, 0) 你的村莊";if(tile.type==="wild")return`(${tile.x}, ${tile.y}) 荒地`;if(tile.cleared)return`(${tile.x}, ${tile.y}) 已清除`;return`(${tile.x}, ${tile.y}) 野獸 ${tile.animals}`}
function mapIcon(tile){if(tile.type==="village")return"🏠";if(tile.type==="oasis")return tile.cleared?"✅":"🌳";if(tile.type==="camp")return tile.cleared?"✅":"🐾";return"🌾"}
function suggestedTroops(target){return Math.max(1,Math.ceil((target.animals*23+45)/unitStats.clubman.attack))}
function formatCost(cost){return["wood","clay","iron","crop"].map(key=>`${resourceLabels[key].icon}${Math.floor(cost[key]||0)}`).join(" ")}
function updateText(id,value){const element=document.getElementById(id);if(element)element.textContent=value}
function setNotice(message,tone=""){const notice=document.getElementById("notice");notice.className=`notice ${tone}`.trim();notice.textContent=message;const status=document.getElementById("saveStatus");if(status)status.textContent=`${message} Google Sheet: ${DB_SHEET_URL}`}
async function syncSheet(){const endpoint=localStorage.getItem(ENDPOINT_KEY);if(!endpoint){setNotice("尚未設定 Apps Script endpoint；目前只會本機存檔。","warn");return}try{const response=await fetch(endpoint,{method:"POST",mode:"cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"save",token:localStorage.getItem(TOKEN_KEY)||"",state,savedAt:new Date().toISOString()})});if(!response.ok)throw new Error(`HTTP ${response.status}`);const result=await response.json();setNotice(result.ok?"已同步到 Google Sheets。":"同步端點回傳錯誤。",result.ok?"success":"warn")}catch(error){setNotice(`同步失敗：${error.message}`,"warn")}}
function exportJson(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="frontier-village-save.json";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setNotice("JSON 存檔已匯出。","success")}
function switchView(viewName){document.querySelectorAll(".nav").forEach(item=>item.classList.toggle("active",item.dataset.view===viewName));document.querySelectorAll(".view").forEach(view=>view.classList.toggle("active-view",view.id===viewName));if(viewName==="reports"){state.progress.report=true;localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}renderQuests()}
function bindEvents(){document.querySelectorAll(".nav").forEach(nav=>nav.addEventListener("click",()=>switchView(nav.dataset.view)));document.getElementById("fieldGrid").addEventListener("click",event=>{const card=event.target.closest("[data-field-id]");if(card)upgradeField(card.dataset.fieldId)});document.getElementById("mapGrid").addEventListener("click",event=>{const tileButton=event.target.closest("[data-tile]");if(!tileButton)return;selectedTargetId=tileButton.dataset.tile;const target=state.map.find(tile=>tile.id===selectedTargetId);if(target?.type==="oasis")state.progress.select=true;setNotice(target?`已選取：${target.name} (${target.x}, ${target.y})。`:"已選取地圖方格。");render()});document.getElementById("trainClubBtn").addEventListener("click",()=>train("clubman",3));document.getElementById("trainSpearBtn").addEventListener("click",()=>train("spearman",2));document.getElementById("trainClubBtnMilitary").addEventListener("click",()=>train("clubman",3));document.getElementById("trainSpearBtnMilitary").addEventListener("click",()=>train("spearman",2));document.getElementById("attackBtn").addEventListener("click",attack);document.getElementById("quickSaveBtn").addEventListener("click",()=>saveLocal("快速存檔完成。","success"));document.getElementById("saveLocalBtn").addEventListener("click",()=>saveLocal());document.getElementById("syncSheetBtn").addEventListener("click",syncSheet);document.getElementById("exportBtn").addEventListener("click",exportJson);document.getElementById("resetBtn").addEventListener("click",()=>{if(!confirm("確定要重置遊戲？"))return;state=freshState();selectedTargetId=null;previousHud={};saveLocal("已重置新遊戲。","success")});document.getElementById("saveEndpointBtn").addEventListener("click",()=>{localStorage.setItem(ENDPOINT_KEY,document.getElementById("endpointInput").value.trim());localStorage.setItem(TOKEN_KEY,document.getElementById("tokenInput").value.trim());setNotice("同步設定已儲存。","success")})}
bindEvents();
render();
setInterval(()=>{tickResources();renderHud()},5000);
