(function(){
  const GAME_KEY='frontier-village-save-v4';
  const BUILDING_KEY='frontier-village-buildings-v1';
  const defs={
    main:{name:'主樓',icon:'🏛️',role:'村莊管理中心',desc:'主樓是村莊核心。先從這裡熟悉村莊，再切到資源或訓練。',base:{wood:160,clay:130,iron:100,crop:70},grow:{wood:64,clay:52,iron:42,crop:30},effect:l=>`管理等級 ${l}`},
    warehouse:{name:'倉庫',icon:'📦',role:'提高資源上限',desc:'倉庫讓資源能存更多。資源快滿時，優先升級這裡。',base:{wood:130,clay:160,iron:90,crop:70},grow:{wood:58,clay:72,iron:42,crop:30},effect:l=>`倉儲上限 +${(l-1)*1500}`},
    barracks:{name:'兵營',icon:'⚔️',role:'訓練士兵',desc:'兵營用來訓練棍棒兵與矛兵。補兵後再去地圖攻擊綠洲。',base:{wood:180,clay:150,iron:170,crop:90},grow:{wood:78,clay:60,iron:72,crop:42},effect:l=>`訓練設施等級 ${l}`},
    rally:{name:'集結點',icon:'🚩',role:'出兵與地圖行動',desc:'集結點用來集合軍隊。準備好後可以直接前往地圖出兵。',base:{wood:110,clay:130,iron:120,crop:80},grow:{wood:48,clay:54,iron:50,crop:32},effect:l=>`出兵指揮等級 ${l}`},
    granary:{name:'穀倉',icon:'🌾',role:'保管穀物',desc:'穀倉讓村莊保留更多穀物，士兵變多後會更重要。',base:{wood:120,clay:110,iron:90,crop:140},grow:{wood:46,clay:44,iron:38,crop:64},effect:l=>`穀物儲備等級 ${l}`},
    marketplace:{name:'市集',icon:'⚖️',role:'後勤與交易',desc:'市集先作為後勤建築，之後可擴充交易與補給。',base:{wood:140,clay:120,iron:110,crop:100},grow:{wood:58,clay:48,iron:44,crop:44},effect:l=>`後勤等級 ${l}`}
  };
  const res={wood:['木材','🪵','伐木場'],clay:['泥土','🧱','泥坑'],iron:['鐵礦','⛓️','鐵礦'],crop:['穀物','🌾','農田']};
  let selected='main';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));

  function injectStyles(){
    if($('#buildingAddonStyles'))return;
    const st=document.createElement('style');
    st.id='buildingAddonStyles';
    st.textContent=`
      html,body{height:100%;overflow:hidden}.game-shell{display:grid;grid-template-rows:auto minmax(0,1fr);height:calc(100dvh - 16px);margin:8px auto}.layout,.content,.sidebar,.view.active-view{min-height:0}.layout{height:100%}.content{display:flex;flex-direction:column;overflow:hidden}.notice{flex:0 0 auto;margin-bottom:10px;padding:8px 10px}.view.active-view{flex:1 1 auto;overflow:hidden}#village.active-view{display:grid;grid-template-rows:minmax(190px,.9fr) auto minmax(210px,1fr);gap:10px}.hero-panel{min-height:0;padding:14px}.quick-stats{margin-top:10px}.village-art{min-height:220px}
      .village-mode-bar{display:grid;grid-template-columns:repeat(3,minmax(92px,auto)) minmax(0,1fr);gap:8px;align-items:center;min-height:46px;border:1px solid rgba(126,105,63,.24);border-radius:8px;padding:7px;background:rgba(255,253,246,.92)}.village-mode{min-height:38px;padding:7px 10px}.village-mode.active{color:#fff;border-color:#2f6436;background:linear-gradient(#6fa34a,#32683c)}.village-coach{min-width:0;color:#6b705f;font-size:.88rem;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
      .village-art .building-hotspot,.village-art .resource-hotspot{position:absolute;z-index:6;display:grid;place-items:center;gap:1px;min-height:54px;padding:4px;color:#2b1d0b;text-align:center;line-height:1.05;cursor:pointer}.village-art .building-hotspot span,.village-art .resource-hotspot span{display:block;font-size:1.15rem}.village-art .building-hotspot b,.village-art .resource-hotspot b{display:block;border-radius:999px;padding:2px 7px;background:rgba(255,250,225,.94);font-size:.72rem;white-space:nowrap}.village-art .building-hotspot:hover,.village-art .building-hotspot.selected,.village-art .resource-hotspot:hover{outline:4px solid rgba(47,103,189,.42);transform:translateY(-2px) scale(1.04);filter:brightness(1.06)}
      .village-workbench{margin-top:0}.building-detail{display:grid;gap:8px}.building-hero{display:grid;grid-template-columns:56px minmax(0,1fr);gap:12px;align-items:center}.building-icon-large{display:grid;width:56px;height:56px;place-items:center;border:1px solid rgba(126,105,63,.26);border-radius:8px;background:linear-gradient(#fff8df,#e9c56a);font-size:1.75rem}.building-stat-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.building-stat-grid div{border:1px solid rgba(126,105,63,.22);border-radius:8px;padding:9px;background:#fbf4df}.building-stat-grid small{display:block;color:#6b705f;font-size:.76rem}.building-stat-grid strong{display:block;margin-top:3px}.building-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.building-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.building-card{display:grid;gap:7px;min-height:104px;padding:9px;text-align:left;background:linear-gradient(135deg,rgba(255,255,255,.82),rgba(255,246,217,.86)),#fff7df}.building-card.selected{color:#fff;border-color:#2f6436;background:linear-gradient(#6fa34a,#32683c)}.building-card-top{display:flex;align-items:center;gap:7px}.building-card-icon{display:grid;width:34px;height:34px;place-items:center;border-radius:8px;background:rgba(255,255,255,.28)}
      .field-grid.compact-fields{grid-template-columns:repeat(4,minmax(130px,1fr));overflow:hidden;gap:10px}.field-grid.compact-fields .field-card{min-height:154px;padding:10px}.field-grid.compact-fields .field-card{cursor:pointer}
      @media(max-width:1120px){.game-shell{width:100%;height:100dvh;margin:0;border-radius:0}.topbar{position:static}.layout{grid-template-columns:156px minmax(0,1fr)}.sidebar{min-height:0;padding:10px}}
      @media(max-width:768px){body{padding-bottom:0}.topbar{padding:7px 8px}.brand{gap:8px}.brand-mark{width:34px;height:34px}.brand p{display:none}.hud-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px;overflow:visible;padding-bottom:0}.hud-item{min-width:0;min-height:46px;grid-template-columns:24px minmax(0,1fr);gap:0 5px;padding:5px}.hud-icon{width:23px;height:23px;font-size:.86rem}.hud-label,.hud-item small{font-size:.66rem}.hud-item strong{font-size:.9rem}.hud-item small:nth-of-type(n+2){display:none}.layout{display:grid;grid-template-rows:auto minmax(0,1fr);height:100%}.sidebar{display:block;padding:6px 8px 0}.task-box{margin:0;padding:0;border:0;background:transparent}.task-box h2,.task-box ol{display:none}.next-step{margin:0;padding:7px 9px;font-size:.78rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.content{padding:8px 8px 72px}.notice{margin-bottom:7px;padding:7px 9px;font-size:.82rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#village.active-view{grid-template-rows:minmax(172px,.88fr) auto minmax(178px,1fr);gap:7px}.hero-panel{gap:7px;padding:8px}.hero-copy{display:grid;grid-template-columns:1fr auto;gap:4px 8px;align-items:center}.hero-copy .eyebrow,.hero-copy h2{margin:0}.hero-copy p:not(.eyebrow),.quick-stats{display:none}.village-art{min-height:158px}.village-mode-bar{grid-template-columns:repeat(3,1fr);gap:5px;min-height:42px;padding:5px}.village-mode{min-height:36px;padding:6px 5px;font-size:.8rem}.village-coach{display:none}.village-workbench{grid-template-columns:1fr}.building-list-panel{display:none}.panel{padding:9px}.inline-head{margin-bottom:7px}.inline-head h2,.section-head h2{font-size:1.08rem}.click-chip{display:none}.building-hero{grid-template-columns:42px minmax(0,1fr);gap:8px}.building-icon-large{width:42px;height:42px;font-size:1.35rem}.building-detail p{font-size:.82rem;line-height:1.35}.building-stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.building-stat-grid div{padding:7px}.building-actions{grid-template-columns:repeat(2,minmax(0,1fr))}.section-head{flex-direction:row;align-items:center;margin:0 0 7px}.compact-row,.button-row{display:flex;width:auto}.compact-row button{min-height:36px;padding:6px 8px;font-size:.78rem}.field-grid.compact-fields{grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.field-grid.compact-fields .field-card{min-height:132px;padding:8px}.field-card .field-meta:nth-of-type(n+3),.field-card .field-cost{display:none}.upgrade-button{min-height:34px;padding:6px 8px}.training-grid{grid-template-columns:1fr;gap:7px}.training-card{padding:9px}.training-stats{grid-template-columns:repeat(4,minmax(0,1fr));gap:5px}.training-stats div{padding:5px}.train-buttons{grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.main-nav{min-height:62px}}
      @media(max-width:430px){.hud-item{min-width:0}#village.active-view{grid-template-rows:minmax(162px,.82fr) auto minmax(174px,1fr)}.village-art{min-height:148px}.wall{inset:24% 16%;border-width:11px}.village-art .building-hotspot,.village-art .resource-hotspot{min-height:44px;transform:scale(.9)}.village-art .building-hotspot b,.village-art .resource-hotspot b{font-size:.64rem}}
    `;
    document.head.appendChild(st);
  }

  function game(){try{return JSON.parse(localStorage.getItem(GAME_KEY)||'null')}catch{return null}}
  function levels(){try{return {...baseLevels(),...(JSON.parse(localStorage.getItem(BUILDING_KEY)||'{}').levels||{})}}catch{return baseLevels()}}
  function baseLevels(){return Object.fromEntries(Object.keys(defs).map(id=>[id,1]))}
  function saveLevels(lv){localStorage.setItem(BUILDING_KEY,JSON.stringify({levels:lv}));const g=game();if(g&&g.village){g.village.buildings=Object.entries(lv).map(([id,level])=>({id,level}));g.lastSaved=new Date().toISOString();localStorage.setItem(GAME_KEY,JSON.stringify(g))}}
  function resources(){return game()?.village?.resources||{wood:760,clay:760,iron:760,crop:760}}
  function cost(id,level){const d=defs[id];return Object.fromEntries(Object.keys(res).map(k=>[k,Math.round(d.base[k]+d.grow[k]*level)]))}
  function fieldCost(f){const l=Number(f?.level||1);return{wood:80+l*42,clay:70+l*36,iron:55+l*31,crop:35+l*24}}
  function canPay(c){const r=resources();return Object.entries(c).every(([k,v])=>Number(r[k]||0)>=v)}
  function pay(c){const g=game();if(!g?.village?.resources)return;for(const [k,v] of Object.entries(c))g.village.resources[k]=Math.max(0,Number(g.village.resources[k]||0)-v);g.lastSaved=new Date().toISOString();localStorage.setItem(GAME_KEY,JSON.stringify(g));for(const k of Object.keys(res)){const el=document.getElementById(k);if(el)el.textContent=Math.floor(g.village.resources[k]||0).toLocaleString('zh-TW')}}
  function fmt(c){return Object.entries(c).map(([k,v])=>`${res[k][1]}${v}`).join(' ')}
  function notice(msg,tone='success'){const n=document.getElementById('notice');if(n){n.className=`notice ${tone}`.trim();n.textContent=msg}}

  function ensureBar(){const village=document.getElementById('village'),hero=document.querySelector('#village .hero-panel');if(!village||!hero||document.querySelector('.village-mode-bar'))return;const bar=document.createElement('div');bar.className='village-mode-bar';bar.innerHTML=`<button class="village-mode active" data-village-panel="buildings">🏘️ 建築</button><button class="village-mode" data-village-panel="resources">🪵 資源</button><button class="village-mode" data-village-panel="training">⚔️ 訓練</button><span class="village-coach">提示：點主樓、倉庫、兵營或集結點進入建築。</span>`;hero.insertAdjacentElement('afterend',bar)}
  function nodes(panel){if(panel==='buildings')return [document.querySelector('#village .village-workbench')].filter(Boolean);if(panel==='resources'){const wrap=document.getElementById('resourcePanel');if(wrap)return[wrap];const grid=document.getElementById('fieldGrid');return[grid?.previousElementSibling,grid].filter(Boolean)}if(panel==='training'){const wrap=document.getElementById('trainingPanel');if(wrap)return[wrap];const grid=document.getElementById('trainingGridVillage');return[grid?.previousElementSibling,grid].filter(Boolean)}return[]}
  function show(panel='buildings'){const v=document.getElementById('village');if(!v)return;v.dataset.villagePanel=panel;for(const p of ['buildings','resources','training'])for(const n of nodes(p))n.style.display=p===panel?'':'none';document.querySelectorAll('[data-village-panel]').forEach(b=>b.classList.toggle('active',b.dataset.villagePanel===panel));const c=document.querySelector('.village-coach');if(c)c.textContent=panel==='resources'?'提示：資源濃縮為 4 類，直接升最低等級田。':panel==='training'?'提示：補棍棒兵，再去地圖攻擊綠洲。':'提示：點主樓、倉庫、兵營或集結點進入建築。';if(panel==='resources')compactFields()}

  function render(){const detail=document.getElementById('buildingDetail'),grid=document.getElementById('buildingGrid');if(!detail||!grid)return;const lv=levels(),d=defs[selected]||defs.main,l=lv[selected]||1,c=cost(selected,l),ok=canPay(c);detail.innerHTML=`<div class="building-hero"><span class="building-icon-large">${d.icon}</span><div><h3>${d.name} <small>等級 ${l}</small></h3><p>${d.role}</p></div></div><p>${d.desc}</p><div class="building-stat-grid"><div><small>目前效果</small><strong>${d.effect(l)}</strong></div><div><small>升級後</small><strong>${d.effect(l+1)}</strong></div><div><small>升級成本</small><strong>${fmt(c)}</strong></div><div><small>狀態</small><strong>${ok?'資源足夠，可以升級':'資源不足，先收成或模擬時間'}</strong></div></div><div class="building-actions"><button class="primary" data-addon-upgrade="${selected}" ${ok?'':'disabled'}>${ok?'升級'+d.name:'資源不足'}</button>${shortcut(selected)}</div>`;grid.innerHTML=Object.keys(defs).map(id=>`<button type="button" class="building-card ${id===selected?'selected':''}" data-addon-building="${id}"><span class="building-card-top"><span class="building-card-icon">${defs[id].icon}</span><span><strong>${defs[id].name}</strong><small>等級 ${lv[id]||1}</small></span></span><small>${defs[id].role}</small></button>`).join('');document.querySelectorAll('[data-building]').forEach(b=>b.classList.toggle('selected',b.dataset.building===selected))}
  function shortcut(id){if(id==='barracks')return'<button data-addon-panel="training">在本頁訓練</button>';if(id==='rally')return'<button data-addon-view="map">前往地圖出兵</button>';return'<button data-addon-panel="resources">升級資源田</button>'}
  function upgrade(id){const lv=levels(),l=lv[id]||1,c=cost(id,l);if(!canPay(c)){notice('資源不足，請先收成、模擬時間或升級資源田。','warn');render();return}pay(c);lv[id]=l+1;saveLevels(lv);notice(`${defs[id].name} 升級成功，現在是等級 ${lv[id]}。`);render()}

  function compactFields(){const grid=document.getElementById('fieldGrid'),g=game();if(!grid||!g?.village?.fields?.length)return;const groups={wood:[],clay:[],iron:[],crop:[]};for(const f of g.village.fields)if(groups[f.type])groups[f.type].push(f);grid.classList.add('compact-fields');grid.innerHTML=Object.entries(groups).map(([type,arr])=>{const target=[...arr].sort((a,b)=>a.level-b.level)[0]||{id:type+'_0',level:1};const total=arr.reduce((s,f)=>s+16+f.level*12,0);const avg=arr.length?arr.reduce((s,f)=>s+f.level,0)/arr.length:1;const c=fieldCost(target),ok=canPay(c);return `<article class="field-card field-${type} ${ok?'affordable':'locked'}" data-upgrade-field="${target.id}"><div class="field-title"><span class="field-icon">${res[type][1]}</span><span class="field-prompt">點擊升級</span></div><strong>${res[type][2]}</strong><span class="field-meta">平均等級 ${avg.toFixed(1)}</span><span class="field-meta">總產量 +${total}/h</span><span class="field-cost">升級最低田：${fmt(c)}</span><button class="upgrade-button" data-upgrade-field="${target.id}" ${ok?'':'disabled'}>${ok?'升級':'資源不足'}</button></article>`}).join('')}

  function bind(){document.addEventListener('click',e=>{const mode=e.target.closest('[data-village-panel]');if(mode)return show(mode.dataset.villagePanel);const hot=e.target.closest('[data-building]');if(hot){selected=hot.dataset.building;show('buildings');notice(`已進入 ${defs[selected].name}。`);render();return}const card=e.target.closest('[data-addon-building]');if(card){selected=card.dataset.addonBuilding;notice(`已進入 ${defs[selected].name}。`);render();return}const up=e.target.closest('[data-addon-upgrade]');if(up&&!up.disabled)return upgrade(up.dataset.addonUpgrade);const panel=e.target.closest('[data-addon-panel]');if(panel)return show(panel.dataset.addonPanel);const view=e.target.closest('[data-addon-view]');if(view)return document.querySelector(`.nav[data-view="${view.dataset.addonView}"]`)?.click();const fj=e.target.closest('[data-field-jump]');if(fj)return show('resources')})}
  function init(){injectStyles();ensureBar();bind();show(document.getElementById('village')?.dataset.villagePanel||'buildings');render();compactFields();setInterval(compactFields,1200)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
